apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 934225420335.dkr.ecr.us-east-1.amazonaws.com/backend:6add4c8accb219d63eb1aa50c4906cc29da034ef
          ports:
            - containerPort: 5000