name: Backend Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and Lint
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd starter/backend && pipenv install --dev

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and Test
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd starter/backend && pipenv install --dev
          pipenv run python -m unittest discover

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application using docker
        run: docker build -t backend:test starter/backend