name: Frontend Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Perform a cache action to restore cache before dependency install
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run the npm run lint command
        run: npm run lint
        working-directory: starter/frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Perform a cache action to restore cache before dependency install
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run the npm run test command
        run: npm run test -- --watchAll=false
        working-directory: starter/frontend

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build application using docker with build-args
        env:
          REGISTRY: 063446971241.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: frontend
          IMAGE_TAG: latest
          MOVIE_API_URL: http://a2967ed1bf3674044900553ececb44f0-1803059679.us-east-1.elb.amazonaws.com
        run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=$MOVIE_API_URL -t $REGISTRY/$REPOSITORY:$IMAGE_TAG starter/frontend
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig and Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name cluster
          kubectl rollout restart deployment/frontend
